### ISSUE TITLE
java.lang.NoSuchMethodError: No super method getAdapterPositionFor(Landroidx/recyclerview/widget/RecyclerView$ViewHolder;)

### ISSUE THREAD

**Issue by jplipata** [Omega-R/OmegaRecyclerView#109]
I am using AndroidX and am getting a crash in Release (not Debug)

    implementation 'com.github.Omega-R:OmegaRecyclerView:1.7.6@aar'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'

I suspect this may be a ProGuard issue?

From Crashlytics:

```
Fatal Exception: java.lang.NoSuchMethodError: No super method getAdapterPositionFor(Landroidx/recyclerview/widget/RecyclerView$ViewHolder;)I in class Landroidx/recyclerview/widget/RecyclerView; or its super classes (declaration of 'androidx.recyclerview.widget.RecyclerView' appears in /data/app/com.mydomain.myapp-gQlqDSAsbaNKIg0how5GmQ==/base.apk)
       at androidx.appcompat.widget.ExpandedRecyclerView.getAdapterPositionFor(ExpandedRecyclerView.java:23)
       at com.omega_r.libs.omegarecyclerview.OmegaRecyclerView.getAdapterPositionFor(OmegaRecyclerView.java:398)
       at androidx.recyclerview.widget.RecyclerView$ViewHolder.getAdapterPosition(RecyclerView.java:10940)
       at androidx.recyclerview.widget.RecyclerView.getChildAdapterPosition(RecyclerView.java:4629)
       at com.omega_r.libs.omegarecyclerview.sticky_header.StickyHeaderDecoration.getItemOffsets(StickyHeaderDecoration.java:36)
       at androidx.recyclerview.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:4909)
       at androidx.recyclerview.widget.LinearLayoutManager.androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(LinearLayoutManager.java:30106)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.findFirstDependency(AppBarLayout.java:1556)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:782)
       at android.view.View.layout(View.java:19654)
       at android.view.ViewGroup.layout(ViewGroup.java:6127)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2584)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2293)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1451)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7204)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
       at android.view.Choreographer.doCallbacks(Choreographer.java:791)
       at android.view.Choreographer.doFrame(Choreographer.java:726)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

**Comment by R12rus** [comment]
Fixed in 1.9.0.
Try this one implementation 'com.github.Omega-R:OmegaRecyclerView:1.9.0@aar' // AndroidX
